spring:
 jpa:
  hibernate:
   ddl-auto: none
  properties:
   hibernate:
    generate_statistics: true
    batch_size: 30
    order_insert: true
 datasource:
  url: jdbc:mysql://localhost:3306/accesslog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&rewriteBatchedStatements=true
  username: accesslog
  password: accesslog
