spring:
 jpa:
  hibernate:
   ddl-auto: none
  properties:
   hibernate:
    #generate_statistics: true
    jdbc:
     batch_size: 100
     time_zone: UTC
    order_insert: true
 datasource:
  url: jdbc:mysql://localhost:3306/accesslog?useUnicode=true&useJDBCCompliantTimezoneShift=false&useLegacyDatetimeCode=false&serverTimezone=UTC&rewriteBatchedStatements=true
  username: accesslog
  password: accesslog
